#!/usr/bin/env python3
"""Generate the Go port of src/sec_af/compliance/mapping.py::COMPLIANCE_MAP.

The table is ~34 CWEs x 5 framework controls of hand-written strings; typing it
out again in Go would be an invitation to a silent transcription error, so it is
mechanically derived from the Python module instead.

Two artifacts are written, both committed:

  internal/compliance/table_gen.go        the Go table (compile-time checked)
  internal/compliance/testdata/compliance_map.json
                                          the same table as JSON, which
                                          table_test.go compares the compiled Go
                                          table against - so a hand edit to the
                                          generated Go file fails the build gate.

Run (from the repo root of the worktree):

    PYTHONPATH=src ~/.agentfield/packages/sec-af/venv/bin/python \
        go/scripts/gen_compliance_table.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GO_ROOT = REPO_ROOT / "go"
sys.path.insert(0, str(REPO_ROOT / "src"))

from sec_af.compliance.mapping import COMPLIANCE_MAP  # noqa: E402


def go_string(value: str) -> str:
    """Render value as a Go interpreted string literal.

    Non-ASCII characters are emitted verbatim (Go source is UTF-8 and gofmt
    keeps them), so the section sign in the HIPAA control ids stays readable.
    """
    out = ['"']
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def render_go() -> str:
    lines: list[str] = [
        "// Code generated by scripts/gen_compliance_table.py. DO NOT EDIT.",
        "",
        "package compliance",
        "",
        'import "github.com/Agent-Field/sec-af/go/internal/schemas"',
        "",
        "// ComplianceMap ports the module-level COMPLIANCE_MAP table of",
        "// src/sec_af/compliance/mapping.py: the static CWE -> framework-control",
        "// mapping every finding is scored against.",
        "//",
        "// Key order below is the Python dict's literal (insertion) order, and each",
        "// value keeps the Python list order, because GetComplianceMappings returns the",
        "// per-CWE list verbatim and callers compare it positionally.",
        "//",
        "// Regenerate with:",
        "//",
        "//\tPYTHONPATH=src ~/.agentfield/packages/sec-af/venv/bin/python \\",
        "//\t    go/scripts/gen_compliance_table.py",
        "var ComplianceMap = map[string][]schemas.ComplianceMapping{",
    ]
    for cwe, mappings in COMPLIANCE_MAP.items():
        lines.append(f"\t{go_string(cwe)}: {{")
        for mapping in mappings:
            lines.append(
                "\t\t{"
                f"Framework: {go_string(mapping.framework)}, "
                f"ControlID: {go_string(mapping.control_id)}, "
                f"ControlName: {go_string(mapping.control_name)}"
                "},"
            )
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_json() -> str:
    payload = {
        cwe: [
            {
                "framework": mapping.framework,
                "control_id": mapping.control_id,
                "control_name": mapping.control_name,
            }
            for mapping in mappings
        ]
        for cwe, mappings in COMPLIANCE_MAP.items()
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    go_path = GO_ROOT / "internal" / "compliance" / "table_gen.go"
    json_path = GO_ROOT / "internal" / "compliance" / "testdata" / "compliance_map.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    _ = go_path.write_text(render_go(), encoding="utf-8")
    _ = json_path.write_text(render_json(), encoding="utf-8")
    print(f"wrote {go_path} ({len(COMPLIANCE_MAP)} CWEs)")
    print(f"wrote {json_path}")


if __name__ == "__main__":
    main()
