package output

import (
	"strings"
	"testing"
)

// This file covers output/report.py behaviours the Python suite's single
// substring test (ported in json_output_test.go) does not reach. The
// whole-document parity check lives in golden_test.go.

// TestReportEmptySections covers every "nothing to report" branch of
// generate_report at once, via the empty fixture.
func TestReportEmptySections(t *testing.T) {
	report := GenerateReport(loadFixture(t, "audit_result_empty"))
	for _, want := range []string{
		"- Branch: n/a",
		"No findings.",
		"No attack chains.",
		"No compliance gaps.",
		"  - n/a",
	} {
		if !strings.Contains(report, want) {
			t.Errorf("report is missing %q", want)
		}
	}
}

// TestReportBranchTruthiness pins that an EMPTY branch renders "n/a" like a
// null one — Python tests `if result.branch`, not `is not None`. The edge
// fixture carries branch="".
func TestReportBranchTruthiness(t *testing.T) {
	report := GenerateReport(loadFixture(t, "audit_result_edge"))
	if !strings.Contains(report, "- Branch: n/a") {
		t.Error("an empty branch must render \"- Branch: n/a\"")
	}
	if strings.Contains(report, "- Branch: ``") {
		t.Error("an empty branch was rendered as an empty code span")
	}
}

// TestReportChainStepFallback pins `finding.chain_step or '?'`: the edge
// fixture's dup-a has chain_step 0, which is falsy.
func TestReportChainStepFallback(t *testing.T) {
	report := GenerateReport(loadFixture(t, "audit_result_edge"))
	if !strings.Contains(report, "- Chain: `chain-x` step ?") {
		t.Error("a chain_step of 0 must render as \"?\"")
	}
}

// TestChainStepLabel covers the helper directly.
func TestChainStepLabel(t *testing.T) {
	zero := 0
	one := 1
	cases := []struct {
		in   *int
		want string
	}{
		{nil, "?"},
		{&zero, "?"},
		{&one, "1"},
	}
	for _, tc := range cases {
		if got := chainStepLabel(tc.in); got != tc.want {
			t.Errorf("chainStepLabel(%v) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestReportOmitsEmptyRationale pins the `if finding.rationale:` guard: the
// edge fixture's dup-a has an empty rationale and must not get the line.
func TestReportOmitsEmptyRationale(t *testing.T) {
	report := GenerateReport(loadFixture(t, "audit_result_edge"))
	if strings.Contains(report, "- Rationale: \n") || strings.HasSuffix(report, "- Rationale: ") {
		t.Error("an empty rationale produced a bare \"- Rationale:\" line")
	}
	// The finding that DOES have one still gets it.
	if !strings.Contains(report, "- Rationale: Confirmed by trace.") {
		t.Error("a non-empty rationale is missing")
	}
}

// TestReportHasNoTrailingNewline pins Python's `"\n".join(lines)`, which ends
// the document on the last content line.
func TestReportHasNoTrailingNewline(t *testing.T) {
	for _, name := range goldenFixtures {
		report := GenerateReport(loadFixture(t, name))
		if strings.HasSuffix(report, "\n") {
			t.Errorf("%s: report ends with a newline", name)
		}
	}
}

// TestComplianceReportHasNoTrailingNewline pins the same for the compliance
// report, whose last line is the generator credit.
func TestComplianceReportHasNoTrailingNewline(t *testing.T) {
	for _, name := range goldenFixtures {
		report := GenerateComplianceReportAt(loadFixture(t, name), goldenComplianceReportAt)
		if strings.HasSuffix(report, "\n") {
			t.Errorf("%s: compliance report ends with a newline", name)
		}
		if !strings.HasSuffix(report, "*Report generated by SEC-AF -- Composite Intelligence Security Auditor*") {
			t.Errorf("%s: compliance report does not end with the credit line", name)
		}
	}
}

// TestReportDataFlowTrace pins the trace block, which only appears when the
// proof carries steps.
func TestReportDataFlowTrace(t *testing.T) {
	withTrace := GenerateReport(loadFixture(t, "audit_result"))
	if !strings.Contains(withTrace, "- Data flow trace:\n  - `src/routes.py:15` - Input source") {
		t.Error("the data flow trace block is missing or malformed")
	}
	withoutTrace := GenerateReport(loadFixture(t, "audit_result_report"))
	if strings.Contains(withoutTrace, "- Data flow trace:") {
		t.Error("a finding with no proof produced a data flow trace block")
	}
}
