// Code generated by scripts/gen_compliance_table.py. DO NOT EDIT.

package compliance

import "github.com/Agent-Field/sec-af/go/internal/schemas"

// ComplianceMap ports the module-level COMPLIANCE_MAP table of
// src/sec_af/compliance/mapping.py: the static CWE -> framework-control
// mapping every finding is scored against.
//
// Key order below is the Python dict's literal (insertion) order, and each
// value keeps the Python list order, because GetComplianceMappings returns the
// per-CWE list verbatim and callers compare it positionally.
//
// Regenerate with:
//
//	PYTHONPATH=src ~/.agentfield/packages/sec-af/venv/bin/python \
//	    go/scripts/gen_compliance_table.py
var ComplianceMap = map[string][]schemas.ComplianceMapping{
	"CWE-78": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-79": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-89": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-90": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-91": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-94": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-917": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A03:2021", ControlName: "Injection"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-287": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A07:2021", ControlName: "Identification and Authentication Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(d)", ControlName: "Person or entity authentication"},
		{Framework: "ISO27001", ControlID: "A.5.17", ControlName: "Authentication information"},
	},
	"CWE-306": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A07:2021", ControlName: "Identification and Authentication Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.5.15", ControlName: "Access control"},
	},
	"CWE-352": {
		{Framework: "PCI-DSS", ControlID: "Req 6.2.4", ControlName: "Custom software addresses common coding vulnerabilities"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.8.5", ControlName: "Secure authentication"},
	},
	"CWE-862": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.5.15", ControlName: "Access control"},
	},
	"CWE-863": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.5.18", ControlName: "Access rights"},
	},
	"CWE-326": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(2)(iv)", ControlName: "Encryption and decryption"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-327": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(2)(iv)", ControlName: "Encryption and decryption"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-328": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(2)(iv)", ControlName: "Encryption and decryption"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-330": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-916": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A07:2021", ControlName: "Identification and Authentication Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(d)", ControlName: "Person or entity authentication"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-840": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A04:2021", ControlName: "Insecure Design"},
		{Framework: "HIPAA", ControlID: "§164.308(a)(1)(ii)(A)", ControlName: "Risk analysis"},
		{Framework: "ISO27001", ControlID: "A.8.25", ControlName: "Secure development lifecycle"},
	},
	"CWE-841": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A04:2021", ControlName: "Insecure Design"},
		{Framework: "HIPAA", ControlID: "§164.308(a)(1)(ii)(A)", ControlName: "Risk analysis"},
		{Framework: "ISO27001", ControlID: "A.8.25", ControlName: "Secure development lifecycle"},
	},
	"CWE-200": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.8.12", ControlName: "Data leakage prevention"},
	},
	"CWE-209": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A09:2021", ControlName: "Security Logging and Monitoring Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(b)", ControlName: "Audit controls"},
		{Framework: "ISO27001", ControlID: "A.8.15", ControlName: "Logging"},
	},
	"CWE-312": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(2)(iv)", ControlName: "Encryption and decryption"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-319": {
		{Framework: "PCI-DSS", ControlID: "Req 4", ControlName: "Protect cardholder data with strong cryptography during transmission"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(e)(1)", ControlName: "Transmission security"},
		{Framework: "ISO27001", ControlID: "A.8.20", ControlName: "Network security"},
	},
	"CWE-532": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A09:2021", ControlName: "Security Logging and Monitoring Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(b)", ControlName: "Audit controls"},
		{Framework: "ISO27001", ControlID: "A.8.15", ControlName: "Logging"},
	},
	"CWE-829": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC8", ControlName: "Change management"},
		{Framework: "OWASP", ControlID: "A08:2021", ControlName: "Software and Data Integrity Failures"},
		{Framework: "HIPAA", ControlID: "§164.308(a)(1)(ii)(B)", ControlName: "Risk management"},
		{Framework: "ISO27001", ControlID: "A.8.25", ControlName: "Secure development lifecycle"},
	},
	"CWE-1104": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC8", ControlName: "Change management"},
		{Framework: "OWASP", ControlID: "A06:2021", ControlName: "Vulnerable and Outdated Components"},
		{Framework: "HIPAA", ControlID: "§164.308(a)(1)(ii)(B)", ControlName: "Risk management"},
		{Framework: "ISO27001", ControlID: "A.8.8", ControlName: "Management of technical vulnerabilities"},
	},
	"CWE-16": {
		{Framework: "PCI-DSS", ControlID: "Req 2", ControlName: "Apply secure configurations to all system components"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A05:2021", ControlName: "Security Misconfiguration"},
		{Framework: "HIPAA", ControlID: "§164.308(a)(1)(ii)(B)", ControlName: "Risk management"},
		{Framework: "ISO27001", ControlID: "A.8.9", ControlName: "Configuration management"},
	},
	"CWE-259": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A07:2021", ControlName: "Identification and Authentication Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(d)", ControlName: "Person or entity authentication"},
		{Framework: "ISO27001", ControlID: "A.5.17", ControlName: "Authentication information"},
	},
	"CWE-321": {
		{Framework: "PCI-DSS", ControlID: "Req 3", ControlName: "Protect stored account data"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A02:2021", ControlName: "Cryptographic Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(2)(iv)", ControlName: "Encryption and decryption"},
		{Framework: "ISO27001", ControlID: "A.8.24", ControlName: "Use of cryptography"},
	},
	"CWE-798": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A07:2021", ControlName: "Identification and Authentication Failures"},
		{Framework: "HIPAA", ControlID: "§164.312(d)", ControlName: "Person or entity authentication"},
		{Framework: "ISO27001", ControlID: "A.5.17", ControlName: "Authentication information"},
	},
	"CWE-285": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.5.15", ControlName: "Access control"},
	},
	"CWE-346": {
		{Framework: "PCI-DSS", ControlID: "Req 8", ControlName: "Identify users and authenticate access to system components"},
		{Framework: "SOC2", ControlID: "CC6", ControlName: "Logical and physical access controls"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(a)(1)", ControlName: "Access control"},
		{Framework: "ISO27001", ControlID: "A.5.16", ControlName: "Identity management"},
	},
	"CWE-601": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A01:2021", ControlName: "Broken Access Control"},
		{Framework: "HIPAA", ControlID: "§164.312(c)(1)", ControlName: "Integrity"},
		{Framework: "ISO27001", ControlID: "A.8.28", ControlName: "Secure coding"},
	},
	"CWE-918": {
		{Framework: "PCI-DSS", ControlID: "Req 6", ControlName: "Develop and maintain secure systems and software"},
		{Framework: "SOC2", ControlID: "CC7", ControlName: "System operations"},
		{Framework: "OWASP", ControlID: "A10:2021", ControlName: "Server-Side Request Forgery"},
		{Framework: "HIPAA", ControlID: "§164.312(e)(1)", ControlName: "Transmission security"},
		{Framework: "ISO27001", ControlID: "A.8.20", ControlName: "Network security"},
	},
}
